AWSTemplateFormatVersion: "2010-09-09"
Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: Lab-Migracion-datos-VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: myVPC Internet Gateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: 'true'
      AvailabilityZone: !Select
        - '0'
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: Lab-Migracion-datos-Subnet

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Public Route Table

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  NFSInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09d3b3274b6c5d4aa
      BlockDeviceMappings: 
      - DeviceName: "/dev/xvda"
        Ebs: 
          VolumeType: "standard"
          DeleteOnTermination: "true"
          VolumeSize: "8"
      SecurityGroupIds: 
        - !Ref NFSInstanceSecurityGroup
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: "Name"
          Value: "Servidor NFS"
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            yum update -y
            service nfs start
            echo "/mnt/nfs *(rw,sync,no_subtree_check,no_root_squash)" >> /etc/exports
            mkdir /mnt/nfs
            cd /mnt/nfs
            wget https://github.com/chadwickbureau/baseballdatabank/archive/master.zip
            unzip master.zip
            rm master.zip
            chmod 755 /mnt/nfs
            exportfs -a
            service nfs restart

  ClientInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09d3b3274b6c5d4aa
      BlockDeviceMappings: 
      - DeviceName: "/dev/xvda"
        Ebs: 
          VolumeType: "standard"
          DeleteOnTermination: "true"
          VolumeSize: "8"
      SecurityGroupIds: 
        - !Ref 'ClientInstanceSecurityGroup'
      SubnetId: !Ref PublicSubnet 
      Tags:
        - Key: "Name"
          Value: "Instancia cliente"
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            yum update -y
            cd /home/ec2-user/
            mkdir nas
            wget https://github.com/chadwickbureau/baseballdatabank/archive/refs/tags/v2022.2.zip
            unzip v2022.2.zip
            rm v2022.2.zip
            mv baseballdatabank-2022.2 /home/ec2-user/baseball-data-2021-version
            
  ClientInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref VPC
  
  ClientInstanceSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Security group rule
      GroupId: !Ref ClientInstanceSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      SourceSecurityGroupId: !Ref ClientInstanceSecurityGroup

  NFSInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable access to NFS ports and SSH.
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '2049'
        ToPort: '2049'
        CidrIp: 10.0.0.0/24
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 10.0.0.0/24
      VpcId: !Ref VPC
  
  EC2Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: /
      Roles: 
       - !Ref EC2Role

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join 
        - '-'
        - - 'data-migration-lab'
          - !Ref AWS::AccountId
          - !Select 
            - 0
            - !Split 
              - '-'
              - !Select 
                - 2
                - !Split 
                  - /
                  - !Ref AWS::StackId     
Outputs:
  NFSInstancePrivateIP:
    Description: Direcccion IP privada de la instancia NFS
    Value: !GetAtt NFSInstance.PrivateIp
  ClientInstancePrivateIP:
    Description: Direcccion IP privada de la instancia Cliente
    Value: !GetAtt ClientInstance.PrivateIp
  S3BucketName:
    Description: Bucket Amazon S3 (destino de los datos)
    Value: !Ref S3Bucket