AWSTemplateFormatVersion: '2010-09-09'
Description: Esta plantilla despliega dos funciones lambda que permite encender y apagar un servidor SFTP de la familia AWS Transfer
Parameters: 
  server: 
    Description: ID del servidor SFTP AWS Transfer
    Type: String
Resources:
  StopTransferSFTPServer:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.8
      Role: !GetAtt Role.Arn
      Handler: index.lambda_handler
      Timeout: 10
      Environment:
         Variables:
          server: !Ref server
      Code:
        ZipFile: |
          import boto3
          import os
          region = 'us-east-1'
          server = os.environ['server']
          transfer = boto3.client('transfer', region_name=region)
          def lambda_handler(event, context):
            transfer.stop_server(ServerId=server)
            print('Stopped your server: ' + str(server))
      Description: Function that stops instances

  StartTransferSFTPServer:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.8
      Role: !GetAtt Role.Arn
      Handler: index.lambda_handler
      Timeout: 10
      Environment:
         Variables:
          server: !Ref server
      Code:
        ZipFile: |
          import boto3
          import os
          region = 'us-east-1'
          server = os.environ['server']
          transfer = boto3.client('transfer', region_name=region)
          def lambda_handler(event, context):
            transfer.start_server(ServerId=server)
            print('Stopped your server: ' + str(server))
      Description: Function that starts server

  Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: TransferStartStopPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
                Resource: '*'
              - Effect: Allow
                Action:
                - "transfer:Start*"
                - "transfer:Stop*"
                Resource: '*'
Outputs:
  StopFunction:
    Description: Nombre funcion Lambda
    Value: !Ref StopTransferSFTPServer
  StartFunction:
    Description: Nombre funcion Lambda
    Value: !Ref StartTransferSFTPServer